export const APPS = [
  {
    id: 'techasset',
    name: 'Techasset',
    initial: 'T',
    url: 'https://techasset.bauhub.online',
    en: {
      tag: 'Operations',
      short: 'School ops & inventory',
      desc: 'Smart school operations and asset management — track classroom status, inventory, tasks, loans, fleet resources and daily logistics in one place.',
    },
    es: {
      tag: 'Operaciones',
      short: 'Operaciones escolares',
      desc: 'Gestión inteligente de flota, aulas, inventario, tareas, préstamos, agenda y operaciones escolares en un solo lugar.',
    },
  },
  {
    id: 'horaria',
    name: 'Horaria',
    initial: 'H',
    url: 'https://horaria.bauhub.online',
    en: {
      tag: 'Scheduling',
      short: 'Smart timetables',
      desc: 'Intelligent school scheduling without endless spreadsheets. Organize teachers, classes, classrooms and campuses — clear, automatic, conflict-free.',
    },
    es: {
      tag: 'Horarios',
      short: 'Horarios inteligentes',
      desc: 'Horarios escolares inteligentes. Docentes, cursos, aulas y sedes organizados de forma automática, clara y sin conflictos.',
    },
  },
  {
    id: 'checkinout',
    name: 'Checkinout',
    initial: 'C',
    url: 'https://checkinout.bauhub.online',
    en: {
      tag: 'Access',
      short: 'Visitor flow',
      desc: 'A visitor check-in and check-out system that simplifies school entry and exit flows in a secure, efficient way.',
    },
    es: {
      tag: 'Accesos',
      short: 'Ingreso y egreso',
      desc: 'Sistema de ingreso y egreso de visitantes. Flujos de entrada y salida más simples, ágiles y seguros.',
    },
  },
  {
    id: 'nexo',
    name: 'NexoEscolar',
    initial: 'N',
    url: 'https://nexoescolar.bauhub.online',
    en: {
      tag: 'Permissions',
      short: 'Family permissions',
      desc: 'A school authorization platform that simplifies family permissions and saves schools hours of administrative work.',
    },
    es: {
      tag: 'Autorizaciones',
      short: 'Comunicación con familias',
      desc: 'Plataforma de autorizaciones y comunicación escolar. Acerca a la institución y a las familias, ahorrando horas de gestión.',
    },
  },
  {
    id: 'fugas',
    name: 'Fuga$',
    initial: 'F',
    url: 'https://fugas.bauhub.online',
    en: {
      tag: 'Finance',
      short: 'Personal finance',
      desc: 'A personal finance app that helps users make smarter decisions through analytics, clarity and better money tracking.',
    },
    es: {
      tag: 'Finanzas',
      short: 'Finanzas personales',
      desc: 'Finanzas personales con analíticas claras que apoyan mejores decisiones, sin perderse en los detalles.',
    },
  },
  {
    id: 'typely',
    name: 'Typely',
    initial: 'Y',
    url: 'https://typely.bauhub.online',
    en: {
      tag: 'Typing',
      short: 'Gamified typing',
      desc: 'Gamified typing practice to learn to write faster, better and with more confidence — focused, playful and addictive.',
    },
    es: {
      tag: 'Mecanografía',
      short: 'Mecanografía gamificada',
      desc: 'Práctica de mecanografía gamificada para aprender a escribir más rápido, mejor y con más confianza.',
    },
  },
];

export const COPY = {
  en: {
    nav: ['Home', 'Apps', 'Contact'],
    wordmark: 'BauHub',
    heroLabel: 'A DIGITAL PRODUCT STUDIO',
    manifesto: 'Apps that solve real problems.',
    subhead: 'An ecosystem of tools crafted for education, management, operations and everyday clarity.',
    bySignature: 'by Bautista Goñi',
    exploreApps: 'Explore apps',
    contactMe: 'Contact',
    openApp: 'Open app',
    ecosystemLabel: 'ECOSYSTEM',
    ecosystemHeading: 'An ecosystem of apps.',
    ecosystemSub: 'Everything an institution needs, in one orbit.',
    scrollHint: 'Scroll to explore',
    contactHeader: "Let's build something",
    contactSub: 'Custom apps, consulting and collaboration. I read every message.',
    emailBtn: 'Email me',
    whatsappBtn: 'WhatsApp',
    formName: 'Your name',
    formEmail: 'Your email',
    formMessage: 'What are you working on?',
    formSend: 'Send message',
    footerTagline: '© 2026 BauHub — designed & built by Bautista Goñi',
    footerLinks: 'Apps',
    langToggle: 'ES',
  },
  es: {
    nav: ['Inicio', 'Apps', 'Contacto'],
    wordmark: 'BauHub',
    heroLabel: 'ESTUDIO DE PRODUCTOS DIGITALES',
    manifesto: 'Apps que resuelven problemas reales.',
    subhead: 'Un ecosistema de herramientas creadas para educación, gestión, operaciones y productividad.',
    bySignature: 'Por Bautista Goñi',
    exploreApps: 'Explorar apps',
    contactMe: 'Contacto',
    openApp: 'Abrir app',
    ecosystemLabel: 'ECOSISTEMA',
    ecosystemHeading: 'Un ecosistema de apps.',
    ecosystemSub: 'Todo lo que una institución necesita, en una sola órbita.',
    scrollHint: 'Deslizá para explorar',
    contactHeader: 'Hablemos',
    contactSub: 'Desarrollo de apps, colaboración y soluciones digitales para educación.',
    emailBtn: 'Escribirme',
    whatsappBtn: 'WhatsApp',
    formName: 'Tu nombre',
    formEmail: 'Tu email',
    formMessage: '¿En qué estás trabajando?',
    formSend: 'Enviar mensaje',
    footerTagline: '© 2026 BauHub — diseñado y construido por Bautista Goñi',
    footerLinks: 'Apps',
    langToggle: 'EN',
  },
};
